### PR TITLE
Support react >16

### PR DESCRIPTION
**Pull request by revmischa**

### CODE REVIEW

**Review by jeremy-wischusen-colpal — APPROVED** [review]
Any idea on a timeline for when this will be merged? The rest of my project requires 17 and this is still looking for 16 and it is causing errors when doing npm install.

**Comment by JosefLitos** [comment]
I hope the author will take a look at it soon. Also the material-ui should be updated to mui.

**Comment by jimmytricks** [comment]
Any update on this? Would be great to have this working with React >16? Cheers

**Comment by leMaik** [comment]
Totally forgot about this. I'll release asap.

**Comment by leMaik** [comment]
Fixed in v1.0.1

**Comment by DeividhyTonetti** [comment]
With node v18 or higher, do you have a date?

**Pull request merged**
